#debug: true
spring:
  profiles:
    active: dev
  thymeleaf:
        cache: false
        mode: LEGACYHTML5
        prefix: classpath:/pages/
        suffix: .html
  jpa:
       properties:
         hibernate:
           dialect: org.hibernate.dialect.MySQL5Dialect
       show-sql: true


