spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3369/mall_dev?useUnicode=true&characterEncoding=utf8
      username: root
      password: R25940151
